### ISSUE TITLE
NoSuchDisplayException in gym-duckietown-ros

### ISSUE THREAD

**Issue by liampaull** [duckietown/challenge-aido_LF-baseline-duckietown#11]
```gym-duckietown-ros_1  | Traceback (most recent call last):
gym-duckietown-ros_1  |   File "agent/rosagent.py", line 94, in <module>
gym-duckietown-ros_1  |     r = ROSAgent()
gym-duckietown-ros_1  |   File "agent/rosagent.py", line 16, in __init__
gym-duckietown-ros_1  |     self.env = launch_env()
gym-duckietown-ros_1  |   File "/workspace/agent/env.py", line 17, in launch_env
gym-duckietown-ros_1  |     distortion=True,
gym-duckietown-ros_1  |   File "/workspace/src/gym-duckietown/gym_duckietown/simulator.py", line 225, in __init__
gym-duckietown-ros_1  |     self.shadow_window = pyglet.window.Window(width=1, height=1, visible=False)
gym-duckietown-ros_1  |   File "/root/.local/lib/python2.7/site-packages/pyglet/__init__.py", line 384, in __getattr__
gym-duckietown-ros_1  |     __import__(import_name)
gym-duckietown-ros_1  |   File "/root/.local/lib/python2.7/site-packages/pyglet/window/__init__.py", line 1896, in <module>
gym-duckietown-ros_1  |     gl._create_shadow_window()
gym-duckietown-ros_1  |   File "/root/.local/lib/python2.7/site-packages/pyglet/gl/__init__.py", line 208, in _create_shadow_window
gym-duckietown-ros_1  |     _shadow_window = Window(width=1, height=1, visible=False)
gym-duckietown-ros_1  |   File "/root/.local/lib/python2.7/site-packages/pyglet/window/xlib/__init__.py", line 166, in __init__
gym-duckietown-ros_1  |     super(XlibWindow, self).__init__(*args, **kwargs)
gym-duckietown-ros_1  |   File "/root/.local/lib/python2.7/site-packages/pyglet/window/__init__.py", line 501, in __init__
gym-duckietown-ros_1  |     display = get_platform().get_default_display()
gym-duckietown-ros_1  |   File "/root/.local/lib/python2.7/site-packages/pyglet/window/__init__.py", line 1845, in get_default_display
gym-duckietown-ros_1  |     return pyglet.canvas.get_display()
gym-duckietown-ros_1  |   File "/root/.local/lib/python2.7/site-packages/pyglet/canvas/__init__.py", line 82, in get_display
gym-duckietown-ros_1  |     return Display()
gym-duckietown-ros_1  |   File "/root/.local/lib/python2.7/site-packages/pyglet/canvas/xlib.py", line 86, in __init__
gym-duckietown-ros_1  |     raise NoSuchDisplayException('Cannot connect to "%s"' % name)
gym-duckietown-ros_1  | pyglet.canvas.xlib.NoSuchDisplayException: Cannot connect to "None"```

**Comment by liampaull** [comment]
when running 

    docker-compose -f docker-compose-lf.yml up

in /local

**Comment by liampaull** [comment]
can't reproduce...
