### ISSUE TITLE
Error evaluating my solution

### ISSUE THREAD

**Issue by bramtoula** [duckietown/challenge-aido_LF-baseline-duckietown#6]
```
ERROR:evaluator:Uncaught exception while running Docker Compose:
Traceback (most recent call last):
  File "/project/src/duckietown_challenges_runner/runner.py", line 580, in run_one
    container = client.containers.get(container_id)
  File "/usr/local/lib/python2.7/dist-packages/docker/models/containers.py", line 843, in get
    resp = self.client.api.inspect_container(container_id)
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/container.py", line 730, in inspect_container
    self._get(self._url("/containers/{0}/json", container)), True
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 198, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 537, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=
```

**Comment by liampaull** [comment]
I wonder if this was a duckietown class network related issue ?

**Comment by bramtoula** [comment]
Might be... Didn't happen again after using 
`export DOCKER_CLIENT_TIMEOUT=120` and
`export COMPOSE_HTTP_TIMEOUT=120`
